INSERT INTO genre VALUES (1, 'Action');
INSERT INTO genre VALUES (2, 'Adventure');
INSERT INTO genre VALUES (3, 'Comedy');
INSERT INTO genre VALUES (4, 'Drama');
INSERT INTO genre VALUES (5, 'Fantasy');
INSERT INTO genre VALUES (6, 'Game');
INSERT INTO genre VALUES (7, 'Historical');
INSERT INTO genre VALUES (8, 'Horror');
INSERT INTO genre VALUES (9, 'Isekai');
INSERT INTO genre VALUES (10, 'Magic');
INSERT INTO genre VALUES (11, 'Martial Arts');
INSERT INTO genre VALUES (12, 'Mecha');
INSERT INTO genre VALUES (13, 'Music');
INSERT INTO genre VALUES (14, 'Mystery');
INSERT INTO genre VALUES (15, 'Psychological');
INSERT INTO genre VALUES (16, 'Romance');
INSERT INTO genre VALUES (17, 'Samurai');
INSERT INTO genre VALUES (18, 'School');
INSERT INTO genre VALUES (19, 'Sci-Fi');
INSERT INTO genre VALUES (20, 'Seinen');
INSERT INTO genre VALUES (21, 'Shoujo');
INSERT INTO genre VALUES (22, 'Shounen');
INSERT INTO genre VALUES (23, 'Slice of Life');
INSERT INTO genre VALUES (24, 'Space');
INSERT INTO genre VALUES (25, 'Sports');
INSERT INTO genre VALUES (26, 'Super Power');
INSERT INTO genre VALUES (27, 'Supernatural');
INSERT INTO genre VALUES (28, 'Thriller');
INSERT INTO genre VALUES (29, 'Vampire');
