INSERT INTO genre (id, genre) VALUES (0, 'Action');
INSERT INTO genre (id, genre) VALUES (1, 'Adventure');
INSERT INTO genre (id, genre) VALUES (2, 'Comedy');
INSERT INTO genre (id, genre) VALUES (3, 'Drama');
INSERT INTO genre (id, genre) VALUES (4, 'Fantasy');
INSERT INTO genre (id, genre) VALUES (5, 'Game');
INSERT INTO genre (id, genre) VALUES (6, 'Historical');
INSERT INTO genre (id, genre) VALUES (7, 'Horror');
INSERT INTO genre (id, genre) VALUES (8, 'Isekai');
INSERT INTO genre (id, genre) VALUES (9, 'Magic');
INSERT INTO genre (id, genre) VALUES (10, 'Martial');
INSERT INTO genre (id, genre) VALUES (11, 'Arts');
INSERT INTO genre (id, genre) VALUES (12, 'Mecha');
INSERT INTO genre (id, genre) VALUES (13, 'Music');
INSERT INTO genre (id, genre) VALUES (14, 'Mystery');
INSERT INTO genre (id, genre) VALUES (15, 'Psychological');
INSERT INTO genre (id, genre) VALUES (16, 'Romance');
INSERT INTO genre (id, genre) VALUES (17, 'Samurai');
INSERT INTO genre (id, genre) VALUES (18, 'School');
INSERT INTO genre (id, genre) VALUES (19, 'Science Fiction');
INSERT INTO genre (id, genre) VALUES (20, 'Seinen');
INSERT INTO genre (id, genre) VALUES (21, 'Shoujo');
INSERT INTO genre (id, genre) VALUES (22, 'Shounen');
INSERT INTO genre (id, genre) VALUES (23, 'Slice of Life');
INSERT INTO genre (id, genre) VALUES (24, 'Space');
INSERT INTO genre (id, genre) VALUES (25, 'Sports');
INSERT INTO genre (id, genre) VALUES (26, 'Super Power');
INSERT INTO genre (id, genre) VALUES (27, 'Supernatural');
INSERT INTO genre (id, genre) VALUES (28, 'Thriller');
INSERT INTO genre (id, genre) VALUES (29, 'Tournament');
INSERT INTO genre (id, genre) VALUES (30, 'Vampire');
